[general]
live_config_reload = true

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500 

[window]
decorations = "None"
